MPIC = mpic
MPICFLAGS = -O2 -g -c -Wall -Wno-unused-variable -Wno-unused
.C.o:
	$(MPIC) $(MPICFLAGS) $< -o $@

all: RUBIKS

RUBIKS: RUBIKS.o RUBIKS_SEQENTIAL.o RUBKIKS_PARALLEL.o
	$(MPIC) RUBIKS.o RUBIKS_SEQENTIAL.o RUBKIKS_PARALLEL.o -o RUBKIKS

RUBIKS.o: RUBIKS.c

RUBIKS_SEQENTIAL.o: RUBIKS_SEQENTIAL.c

RUBKIKS_PARALLEL.o: RUBKIKS_PARALLEL.c

clean:
	rm -rf RUBIKS *.o