MPICC = mpicc
MPICCFLAGS = -O2 -g -c -Wall -Wno-unused-variable -Wno-unused
.c.o:
	$(MPICC) $(MPICFLAGS) $< -o $@

all: RUBIKS

RUBIKS: RUBIKS.o RUBIKS_SEQENTIAL.o RUBIKS_PARALLEL.o
	$(MPICC) RUBIKS.o RUBIKS_SEQENTIAL.o RUBIKS_PARALLEL.o -o RUBKIKS

RUBIKS.o: RUBIKS.c RUBIKS.c

RUBIKS_SEQENTIAL.o: RUBIKS_SEQENTIAL.c RUBIKS_SEQENTIAL.h RUBIKS.c

RUBIKS_PARALLEL.o: RUBIKS_PARALLEL.c RUBIKS_PARALLEL.h RUBIKS.c

clean:
	rm -rf RUBIKS *.o